/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as R01ReRendersRouteImport } from './routes/01-re-renders'
import { Route as IndexRouteImport } from './routes/index'

const R01ReRendersRoute = R01ReRendersRouteImport.update({
  id: '/01-re-renders',
  path: '/01-re-renders',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/01-re-renders': typeof R01ReRendersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/01-re-renders': typeof R01ReRendersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/01-re-renders': typeof R01ReRendersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/01-re-renders'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/01-re-renders'
  id: '__root__' | '/' | '/01-re-renders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R01ReRendersRoute: typeof R01ReRendersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/01-re-renders': {
      id: '/01-re-renders'
      path: '/01-re-renders'
      fullPath: '/01-re-renders'
      preLoaderRoute: typeof R01ReRendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R01ReRendersRoute: R01ReRendersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
